@server = http://localhost:61854
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin


### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### -------------------------------CATALOG----------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### Create Demo
POST  {{server}}/catalog/DemoCrud
Accept: application/json
Content-Type: application/json

{ 
  "ID": "b0228336-49f0-4e21-8774-f338750760db"
  "demoName": "Digital Boardroom Retail",
  "demoDescription": "Analytics para Retail :Esta demonstração, destaca a analise  do retail  E2E sendo:Financeiro, Promoções , tendencias das categorias, desenpenho da categoria  , Estoque de loja , demanda da Loja , Gestão de equipe de loja (FTE) , acompanhamento de IoT em loja" ,
  "demoExperience": "",
  "demoStatus": "Ok" ,
  "videoURLEN": "https://video.sap.com/media/t/1_7et0xpd3",
  "videoURLPT": "https://video.sap.com/media/t/1_7et0xpd3"
}

### Upload Binary
PUT {{server}}/catalog/DemoCrud(b0228336-49f0-4e21-8774-f338750760db)/demoImage
Content-Type: image/png

< ./digital.png




### Create Demo
POST  {{server}}/catalog/DemoCrud
Accept: application/json
Content-Type: application/json

{ 
  "ID": "759e90a1-ba07-4afe-b128-902cf9ecf93b",
  "demoName": "Robot Cleaner",
  "demoDescription": "Esta é uma demonstração de ponta a ponta integrada usando um limpador robótico para ajudar a mostrar o poder combinado do SAP BTP , SAP Internet of Things, IOS nativo da Apple e SAP Analytics Cloud para um novo modelo de negócios baseado em consumo. Usando os recursos SAP , vemos como um cliente aproveita esse serviço de limpeza baseado no consumo." ,
  "demoExperience": "Por meio dos dados gerados na IoT , o provedor de serviços tem insights em “tempo real” sobre os robos. O prestador de serviços também tem uma visão clara de todas as ordens de manutenção acionadas automaticamente pelo Robotic cleaner. Isso permite que eles tomem rapidamente as medidas apropriadas para garantir a satisfação do cliente",
  "demoStatus": "Ok" ,
  "videoURLEN": "https://video.sap.com/media/t/1_q4ojv2tr",
  "videoURLPT": "https://video.sap.com/media/t/1_q4ojv2tr"
}

### Upload Binary
PUT {{server}}/catalog/DemoCrud(759e90a1-ba07-4afe-b128-902cf9ecf93b)/demoImage
Content-Type: image/png

< ./robotCleaner.png


### Create Demo
POST  {{server}}/catalog/DemoCrud
Accept: application/json
Content-Type: application/json

{ 
  "ID": "b462f4bc-1319-4f9b-9537-5b44fe373796",
  "demoName": "Smart Dispenser",
  "demoDescription": "Neste cenário, verificamos o uso  máquinas de venda automática inteligentes nas lojas com cartões de fidelidade do cliente para fornecer uma experiência de compra sem vendedores. " ,
  "demoExperience": "",
  "demoStatus": "Ok" ,
  "videoURLEN": "https://video.sap.com/media/t/1_7et0xpd3",
  "videoURLPT": "https://video.sap.com/media/t/1_7et0xpd3"
}

### Upload Binary
PUT {{server}}/catalog/DemoCrud(b462f4bc-1319-4f9b-9537-5b44fe373796)/demoImage
Content-Type: image/png

< ./smartDispenser.png

### Create Demo
POST  {{server}}/catalog/DemoCrud
Accept: application/json
Content-Type: application/json

{ 
  "ID": "c2f45e91-3138-4b16-8656-4895911f47d2",
  "demoName": "Retail Shelf",
  "demoDescription": "Esta é uma história de negócios integrada de ponta a ponta, apresentando a Empresa Inteligente para Varejo. Esta vitrine usa dois aplicativos móveis construídos usando Fiori para IOS e uma prateleira de varejo. O aplicativo Sales Advisor, o assistente de vendas propõe  recomendações personalizadas para clientes dentro da loja. Com o aplicativo In-Store Ops, as tarefas são geradas para ajudar o operador da loja reabastecer com mais eficiência e eficácia" ,
  "demoExperience": "",
  "demoStatus": "Ok" ,
  "videoURLEN": "https://sapvideoa35699dc5.hana.ondemand.com/?entry_id=1_jsme22qc",
  "videoURLPT": "https://sapvideoa35699dc5.hana.ondemand.com/?entry_id=1_jsme22qc"
}

### Upload Binary
PUT {{server}}/catalog/DemoCrud(c2f45e91-3138-4b16-8656-4895911f47d2)/demoImage
Content-Type: image/png

< ./retailShelf.png



### Create Demo
POST  {{server}}/catalog/DemoCrud
Accept: application/json
Content-Type: application/json

{ 
  "ID": "c2f45e91-3138-4b16-8656-4895911f47d2",
  "demoName": "Retail Shelf",
  "demoDescription": "Esta é uma história de negócios integrada de ponta a ponta, apresentando a Empresa Inteligente para Varejo. Esta vitrine usa dois aplicativos móveis construídos usando Fiori para IOS e uma prateleira de varejo. O aplicativo Sales Advisor, o assistente de vendas propõe  recomendações personalizadas para clientes dentro da loja. Com o aplicativo In-Store Ops, as tarefas são geradas para ajudar o operador da loja reabastecer com mais eficiência e eficácia" ,
  "demoExperience": "",
  "demoStatus": "Ok" ,
  "videoURLEN": "https://sapvideoa35699dc5.hana.ondemand.com/?entry_id=1_jsme22qc",
  "videoURLPT": "https://sapvideoa35699dc5.hana.ondemand.com/?entry_id=1_jsme22qc"
}

### Upload Binary
PUT {{server}}/catalog/DemoCrud(c2f45e91-3138-4b16-8656-4895911f47d2)/demoImage
Content-Type: image/png

< ./retailShelf.png


