@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin


### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### -------------------------------CATALOG----------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------






### Read Invoice
GET {{server}}/catalog/Invoice?$expand=invoiceItems
Accept: application/json
Content-Type: application/json
{{basic}}


### Read Invoice Items
GET {{server}}/catalog/InvoiceItems
Accept: application/json
Content-Type: application/json
{{basic}}


### Post Invoice
POST {{server}}/catalog/Invoice
Accept: application/json
Content-Type: application/json
{{basic}}


 {
      "createdAt": "2023-02-02T21:37:39.772Z",
      "createdBy": "savio.marques@sap.com",
      "modifiedAt": "2023-02-02T21:38:58.612Z",
      "modifiedBy": "savio.marques@sap.com",
      "invoiceNumber": "49494",
      "senderName": "ABC",
      "poNumber": "po30304",
      "invoiceType_invoiceType": "MAT",
      "grossAmount": "3000",
      "invoiceDate": "2023-02-02",
      "senderAddress": "Av. Amélia Latorre, 1 T14 AP21",
      "invoiceStatus_invoiceStatus": 1,
      "invoiceItems": [
        {
          "itemNumber": "1",
          "itemDescription": "teste"
        }
      ]
  }


### Read Binary
GET {{server}}/catalog/DemoCrud(f52bf289-5294-4b45-8d73-1ef4475fb5bd)/demoImage

### Update Demo
PUT  {{server}}/catalog/DemoCrud(cf31b7df-51a6-47a2-a860-f6f0e1e1960e)
Accept: application/json
Content-Type: application/json

{ 
  "demoImageURL": "/catalog/DemoCrud(f52bf289-5294-4b45-8d73-1ef4475fb5bd)/demoImage",
}

### Upload Binary
PUT {{server}}/catalog/DemoCrud(775bad1f-c20a-4d98-8fde-f5772f0445fe)/demoImage
Content-Type: image/png

< ./digital.png



### Delete Demo Content
DELETE {{server}}/catalog/DemoCrud(cf31b7df-51a6-47a2-a860-f6f0e1e1960e)/imageContent

### Delete DEMO
DELETE {{server}}/catalog/DemoCrud(f52bf289-5294-4b45-8d73-1ef4475fb5bd)
